version: "3"

volumes:
    PDSC_STACK_DB_VOLUME:
        driver: local

networks:
    pdscnet:

services:
    web:
        image: nginx:latest
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 256M
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /srv/production/www:/var/www/production
            - /srv/production/repository:/var/www/production/repository
            - /srv/staging/www:/var/www/staging
            - /srv/staging/repository:/var/www/staging/repository
            - $PWD/nginx-50words.online.conf:/etc/nginx/conf.d/50words.online.conf
            - $PWD/nginx-staging.50words.online.conf:/etc/nginx/conf.d/staging.50words.online.conf
        networks:
            - pdscnet
