version: "3"

volumes:
    PDSC_STACK_DB_VOLUME:
        driver: local

networks:
    pdscnet:

services:
    web:
        image: nginx:1.15.2-alpine
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 256M
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /srv/50words.online:/var/www/50words.online
            - /srv/50words.online.staging:/var/www/50words.online.staging
            - /srv/staging-repository/repository:/var/www/50words.online.staging/repository
            - $PWD/nginx-50words.online.conf:/etc/nginx/conf.d/50words.online.conf
            - $PWD/nginx-staging.50words.online.conf:/etc/nginx/conf.d/staging.50words.online.conf
        networks:
            - pdscnet
